production:
  server: "https://priv-pub-heroku.herokuapp.com/faye"

#this is the address of this heroku app once youâ€™ve deployed it, plus the `/faye` extension.

  secret_token: <%= Rails.application.secrets.secret_key_for_priv_pub %>
  signature_expiration: 3600 # one day